name: Do all of the things!
on: [push, pull_request]
jobs:
  do-all-of-the-things:
    name: Do all of the things!
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v1
      - name: Print SwiftLint version
        run: swiftlint --version
      - name: Run SwiftLint
        run: swiftlint --strict
      - name: Download DrString
        run: curl --location --remote-name https://github.com/dduan/DrString/releases/latest/download/drstring-x86_64-apple-darwin.tar.gz
      - name: Extract DrString
        run: |
          mkdir drstring-x86_64-apple-darwin
          tar --extract --file drstring-x86_64-apple-darwin.tar.gz --directory drstring-x86_64-apple-darwin
      - name: Add DrString to $PATH
        run: echo "$GITHUB_WORKSPACE/drstring-x86_64-apple-darwin" >> $GITHUB_PATH
      - name: Print DrString version
        run: drstring --version
      - name: Run DrString
        run: drstring check --config-file .drstring.toml
      - name: Run mist tests
        run: swift test || true
      - name: Build mist
        run: swift build --configuration release --arch arm64 --arch x86_64
      - name: Add mist to $PATH
        run: echo "$GITHUB_WORKSPACE/.build/apple/Products/release" >> $GITHUB_PATH
      - name: Print mist version
        run: mist --version
      - name: Print mist list for Firmwares
        run: mist list firmware
      - name: Print mist list for Installers
        run: mist list installer
