name: Unit Tests
on:
  push:
    paths:
      - "**.swift"
  pull_request:
    branches:
      - main
jobs:
  unit_tests:
    name: Unit Tests
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Run Unit Tests
        run: swift test
